export const ALLERGIESLIST_REQUEST = "ALLERGIESLIST_REQUEST";
export const ALLERGIESLIST_SUCCESS = "ALLERGIESLIST_SUCCESS";
export const ALLERGIESLIST_ERROR = "ALLERGIESLIST_ERROR";

export const FAVORITE_FOOD_REQUEST = "FAVORITE_FOOD_REQUEST";
export const FAVORITE_FOOD_SUCCESS = "FAVORITE_FOOD_SUCCESS";
export const FAVORITE_FOOD_ERROR = "FAVORITE_FOOD_ERROR";

export const PERSONALIZED_BREAKFAST_REQUEST = "PERSONALIZED_BREAKFAST_REQUEST";
export const PERSONALIZED_BREAKFAST_SUCCESS = "PERSONALIZED_BREAKFAST_SUCCESS";
export const PERSONALIZED_BREAKFAST_ERROR = "PERSONALIZED_BREAKFAST_ERROR";

export const PERSONALIZED_LUNCH_REQUEST = "PERSONALIZED_LUNCH_REQUEST";
export const PERSONALIZED_LUNCH_SUCCESS = "PERSONALIZED_LUNCH_SUCCESS";
export const PERSONALIZED_LUNCH_ERROR = "PERSONALIZED_LUNCH_ERROR";

export const PERSONALIZED_DINNER_REQUEST = "PERSONALIZED_DINNER_REQUEST";
export const PERSONALIZED_DINNER_SUCCESS = "PERSONALIZED_DINNER_SUCCESS";
export const PERSONALIZED_DINNER_ERROR = "PERSONALIZED_DINNER_ERROR";

export const QUESTIONNAIRES_SELECTION_REQUEST ="QUESTIONNAIRES_SELECTION_REQUEST";
export const UPDATE_QUESTIONNAIRE_DATA = "UPDATE_QUESTIONNAIRE_DATA";
export const CLEARQUESTIONNAIR = "CLEARQUESTIONNAIR";




