export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SOCIAL_REQUEST = "SOCIAL_REQUEST";
export const SOCIAL_SUCCESS = "SOCIAL_SUCCESS";
export const SOCIAL_ERROR = "SOCIAL_ERROR";
export const SOCIAL_RESET = "SOCIAL_RESET";

export const FACEBOOK_EMAIL_REQUEST = "FACEBOOK_EMAIL_REQUEST";
export const FACEBOOK_EMAIL_SUCCESS = "FACEBOOK_EMAIL_SUCCESS";
export const FACEBOOK_EMAIL_ERROR = "FACEBOOK_EMAIL_ERROR";
