export const API = {
  CREATEUSER: "/createuser",
  LOGIN: "/loginuser",
  SOCIALLOGIN: "/sociallogin",
  USERDETAILS: "/userdetails",
  USERDATA: "/userData",
  UPDATEPASSWORD: "/updatepassword",
  UPDATEPROFILE: "/updateprofile",
  FORGETPASSWORD: "/forgotpassword",
  LISTALLERGENS: "/listallergens",
  GETFOOD: "/getfood",
  SAVEFOOD: "/savefoodplan",
  FOODPLAN: "/showfoodplan",
  CHEF: "/getChefFoodPlan",
  FAVORITEFOOD: "/listPrimaryIngredeints",
  CURRENTANDPASTFOODPLAN: "/showPastAndCurrentfoodplan",
  MEALBYTIME: "/getDishesByMealTime",
  PREVIOUSWEEKPLAN: "/getPreviousWeekData",
};
