export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  MENULOGIN: "/menu/login",
  SIGNUP: "/signup",
  PROFILE: "/profile",
  UPDATETIME: "/updatetime",
  EDITUPDATE: "/editProfile",
  SUBSCRIBE: "/subscribe",
  QUESTIONNAIRES: "/questionnaires",
  MEALLANDING: "/meallanding",
  CHECKOUT: "/checkout",
  FORGETPASSWORD: "/forgetPassword",
  BREAKFASTCATALOGUE: "/breakfastfoodcatalogue",
  LUNCHCATALOGUE: "/lunchfoodcatalogue",
  DINNERCATALOGUE: "/dinnerfoodcatalogue",
  FAVORITEFOOD: "/food",
  UPDATEPASSWORD: "/updatepassword",
  MENU: "/menu",
  CHEF: "/chef",
};
