export const GET_FOOD_REQUEST = "GET_FOOD_REQUEST";
export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS";
export const GET_FOOD_ERROR = "GET_FOOD_ERROR";
export const RESET_FOOD_PLAN_REQUEST = "RESET_FOOD_PLAN_REQUEST";

export const EXTRA_ITEM_COUNT_REQUEST = "EXTRA_ITEM_COUNT_REQUEST";
export const REMOVE_DISHES = "REMOVE_DISHES";
export const ADD_SIDE_DISH_REQUEST = "ADD_SIDE_DISH_REQUEST";
export const ADD_DISLIKED_FOOD_REQUEST = "DISLIKED_FOOD_REQUEST";
