export const SAVE_NEXT_WEEK_PLAN_REQUEST = "SAVE_NEXT_WEEK_PLAN_REQUEST";
export const SAVE_NEXT_WEEK_PLAN_SUCCESS = "SAVE_NEXT_WEEK_PLAN_SUCCESS";
export const SAVE_NEXT_WEEK_PLAN_ERROR = "SAVE_NEXT_WEEK_PLAN_ERROR";
