export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const SHOW_FOOD_PLAN_REQUEST = "SHOW_FOOD_PLAN_REQUEST";
export const SHOW_FOOD_PLAN_SUCCESS = "SHOW_FOOD_PLAN_SUCCESS";
export const SHOW_FOOD_PLAN_ERROR = "SHOW_FOOD_PLAN_ERROR";

export const PAST_AND_CURRENT_FOODPLAN_REQUEST='PAST_AND_CURRENT_FOODPLAN_REQUEST'
export const PAST_AND_CURRENT_FOODPLAN_SUCCESS='PAST_AND_CURRENT_FOODPLAN_SUCCESS'
export const PAST_AND_CURRENT_FOODPLAN_ERROR='PAST_AND_CURRENT_FOODPLAN_ERROR'
